services:
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: adminNikiArnel
      RABBITMQ_DEFAULT_PASS: Supergem123&Banane

  # MongoDB Replica Set
  mongo1:
    image: mongo
    container_name: mongo1
    command: --replSet rs0
    ports:
      - "27017:27017"
    volumes:
      - mongo1-data:/data/db

  mongo2:
    image: mongo
    container_name: mongo2
    command: --replSet rs0
    volumes:
      - mongo2-data:/data/db

  mongo3:
    image: mongo
    container_name: mongo3
    command: --replSet rs0
    volumes:
      - mongo3-data:/data/db

  # Publisher Service
  publisher:
    build:
      context: ./stock-publisher
    depends_on:
      - rabbitmq

  # Consumer Service
  consumer:
    build:
      context: ./stock-consumer
    depends_on:
      - rabbitmq
      - mongo1

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data: